### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by SakhavatS** [pablosnt/rekono-cli#35]
**What do you need?**
Remember that you can also mail rekono.project@gmail.com
![Untitled](https://user-images.githubusercontent.com/9460004/217499177-62aeef55-25ce-4965-8b2c-d1d7e9bb1db9.png)

**Comment by pablosnt** [comment]
This error happens during the execution of `npm install .` in the `rekono/frontend` directory. Please, can you execute it manually to check if there is any problem related to your environment?

It hasn't been announced yet, but note that the commands `install`, `update`, `uninstall` and `services` are going to be removed from the `rekono-cli` in the version `2.0.0`. I'm working in new and better ways to install and deploy Rekono on local machines.

**Comment by pablosnt** [comment]
`install` command has been removed in the last `2.0.0` version. You can try [Rekono Desktop](https://github.com/pablosnt/rekono#rekono-desktop) instead, which is a standalone Desktop application that can be installed easily using a DEB file.
